### PR TITLE
Update jQuery to the v3.1

### PR DESCRIPTION
**Pull request by tomasko126**
Signed-off-by: Tomáš Taro tomas@getadblock.com

@kpeckett Could you review?
Thanks :)

### CODE REVIEW

**Comment by itskdog** [comment]
Have you run the (non-minified) migrate plugin to check for jQuery API changes that are unsupported since the previous version we used?

**Comment by tomasko126** [comment]
@kpeckett Good point, I will include jQuery Migrate plugin in my tests and will change the deprecated code, where applicable.

**Comment by tomasko126** [comment]
@kpeckett Ready to review :)

**Comment by itskdog** [comment]
Were these the only changes needed? Did you check the BG page, content script, options pages + other pages (e.g. resourcelist, adreport, popup, .etc)

**Comment by tomasko126** [comment]
@kpeckett Yep, I checked every page.

**Review by itskdog — APPROVED** [review]

**Pull request merged**
