### PR TITLE
Fix for page scroll to top on removing pic

### PR DESCRIPTION
**Pull request by brijeshbhakta30**
Clicking X button for removing picture scrolls the page to top

### CODE REVIEW

**Comment by itskdog** [comment]
Hi!

Thanks for submitting this PR. Can you add some steps to reproduce the issue that should be broken in the current version of CatBlock and fixed in your patch?

Thanks,
Kieran
CatBlock Web Admin

**Comment by brijeshbhakta30** [comment]
Hi Kieran,
Thanks for getting back. When you click the X button for removing the picture that is injected, page scrolls to the top.
I have fixed it in the PR.

Thanks

**Comment by tomasko126** [comment]
This PR looks good to me.

**Comment by tomasko126** [comment]
@kpeckett I will merge this one once I fix the build process for PRs from forked repos.

**Comment by brijeshbhakta30** [comment]
Thanks

**Review by tomasko126 — APPROVED** [review]
LGTM!

**Pull request merged**
