### PR TITLE
Implement WebSocket blocking

### PR DESCRIPTION
**Pull request by tomasko126**
WebSockets can be natively blocked by extensions starting in Chrome 58.

How-to test:
1. Add the following filter: `||pubsub-edge.twitch.tv/v1$websocket`
2. Go to `twitch.tv`
3. Open up the console and verify, that WebSocket requests were blocked

snimka obrazovky 2017-03-08 o 1 33 08

### CODE REVIEW

**Comment by tomasko126** [comment]
@kpeckett In order to test WS blocking, you need to have either Chrome Dev or Canary installed.

**Comment by itskdog** [comment]
If this only works on the current Dev channel, let's wait the feature until it's in Stable.

**Comment by tomasko126** [comment]
@kpeckett Chrome 58 is now stable, I am going to make new changes.

**Comment by tomasko126** [comment]
@kpeckett WS blocking has been rolled out to Chrome Stable, feel free to review and/or merge this PR.

**Review by itskdog — APPROVED** [review]

**Pull request merged**
