### PR TITLE
Remove "Project C.A.T.S." code

### PR DESCRIPTION
**Pull request by tomasko126**
Current "Project C.A.T.S." backers won't be affected by this change

### CODE REVIEW

**Comment by tomasko126** [comment]
@kpeckett Please, take a look and review.
Current backers won't be affected by this change.

You can compare changes in this PR against 44ca859aac0f5948152a9865963bc02b2c81c1ee.

Thanks! :)

**Comment by itskdog** [comment]
Question:
What if C.A.T.S. backers wish to install their version on another computer, but keep the C.A.T.S. images. If they install through /project-cats again, they won't get the images they had before, would they still get the images they backed for?

**Comment by tomasko126** [comment]
@kpeckett For new users, I've added "The Cats Of Project CATS" channel, which is disabled by default. Could you review again? Thanks :)

**Comment by itskdog** [comment]
I'm still unsure why we're removing it. How much does including it affect the install time?

**Comment by tomasko126** [comment]
@kpeckett We have to open our install page right after installation of CatBlock, in order to determine, whether CatBlock should activate "Project C.A.T.S." channel or not.

**Comment by itskdog** [comment]
@tomasko126 and that's bad because...? I'm sure there's a good reason, I'm just not sure what it is

**Review by itskdog — APPROVED** [review]

**Comment by tomasko126** [comment]
@kpeckett Because it takes additional ~30 seconds of extension load. If user, who has just installed CatBlock closes our install page, CatBlock may end up in an uninitialised state and that's the second reason :) On the other side I implemented "Project C.A.T.S." channel, which is disabled by default but can be enabled (only for new users).

**Pull request merged**
