### PR TITLE
Fix #141

### LINKED ISSUE #141: Menu item `Options` is duplicated in context menu of Chrome and Opera
It is duplicated in Chrome:
screen shot 2017-04-25 at 6 49 10 pm

and it is duplicated in Opera:
screen shot 2017-04-25 at 6 44 17 pm

Chrome based browsers add `Options` to the context menu by default, so we don't have to add another `Options` by code.

I will create a pull request for fixing this issue later today.

### PR DESCRIPTION
**Pull request by tsekityam**
Check if the browser is Chrome or Opera, if yes, then don’t add the
options menu item to context menu programmatically.

This is how it looks like in opera
screen shot 2017-04-25 at 11 56 30 pm

and chrome
screen shot 2017-04-25 at 11 55 34 pm

### CODE REVIEW

**Comment by tsekityam** [comment]
I can build it on my MacBook Pro, no idea why the CI build results in failure.

Here is what I did and what I saw
```
Tses-MacBook-Pro:catblock tsekityam$ python2 tools/make_release.py -b chrome -ext zip
Generating CatBlock for Chrome...
Done!
Tses-MacBook-Pro:catblock tsekityam$ python3 tools/make_release.py -b chrome -ext zip
Generating CatBlock for Chrome...
Done!
```

**Comment by itskdog** [comment]
Travis checks against our unit tests (currently unchanged from the ones in the final version of AdBlock 2.x). @tomasko126 - what's the URL for the tests in the extension?

**Comment by tomasko126** [comment]
@tsekityam Thanks for this PR! I will look into, why Travis build failed.

**Comment by tomasko126** [comment]
@kpeckett @tsekityam Looks like the needed private variables keys are not exported to untrusted builds, triggered by pull requests from another repository. I will need to update the script to handle this situation to not test the extension on BrowserStack.

**Review by tomasko126 — APPROVED** [review]
LGTM!

**Comment by tomasko126** [comment]
@tsekityam I am sorry for taking this a bit longer than expected, I had to fix our build infrastructure before accepting this PR.

**Pull request merged**
