### PR TITLE
Enable/Disable replacing ads with pictures

### LINKED ISSUE #14: "Disable CatBlock" button
Should this be in the menu or the options page?

### PR DESCRIPTION
**Pull request by tomasko126**
Fixes #14 

@kpeckett @Jeremyboy222 
Please test & review, thanks!

### CODE REVIEW

**Comment by tomasko126** [comment]
There were also some weird `messages.json` files, which were removed.

**Comment by itskdog** [comment]
Tested with keepvid.com and it works. (sorry about the JSON files, I'm not that good with manual merges so didn't see those files when I merged)

I'm not totally convinced about putting it in the options page. Also the wording makes it seem as if there will be more like this in the future. Is this something we intend to do?

**Comment by itskdog** [comment]
I noticed this on my chromebook when testing:
screenshot 2015-08-18 at 9 43 47 am

The blank checkbox is `enable-display-menu-stats`. The i18n string is `show_on_adblock_menu`.

**Comment by itskdog** [comment]
@tomasko126 Any updates on this? This is all that's blocking 1.3

**Comment by tomasko126** [comment]
@kpeckett I am going to work on this now :)

**Comment by tomasko126** [comment]
@kpeckett Ready for review :)

**Comment by itskdog** [comment]
@tomasko126 The bug I mentioned with `#enable_display_menu_stats[i18n=show_on_adblock_menu]` is still there.

**Comment by itskdog** [comment]
All seems okay - merging.

**Pull request merged**
