### PR TITLE
Check, whether "value" is not undefined, before accessing its value

### LINKED ISSUE #69: "Block an ad" wizard disappears after choosing an element to block
After choosing, what ad should be blocked in the first step of "Block an ad" wizard, the wizard disappears.

This is a regression of #63.

### PR DESCRIPTION
**Pull request by tomasko126**
Fixes #69

### CODE REVIEW

**Comment by itskdog** [comment]
I still don't get why we don't just change this back to a double equals, if that's how it was before.

**Comment by tomasko126** [comment]
@kpeckett In a modern JS environment, only === and !== logical operators should be used since writing a code with both ==/!=  (type-equality comparison) and ===/!== (strict comparison) might lead to unexpected bugs.

**Comment by itskdog** [comment]
But in this case, loose equality is being used to an advantage. It looks
like an external library anyway, so it's probably best not to mess with it.

On 8 Sep 2016 15:54, "Tomáš Taro" notifications@github.com wrote:

@kpeckett https://github.com/kpeckett In a modern JS environment, only
=== and !== logical operators should be used since writing a code with both
==/!= (type-equality comparison) and ===/!== (strict comparison) might lead
to unexpected bugs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/CatBlock/catblock/pull/70#issuecomment-245624725, or mute
the thread

**Comment by tomasko126** [comment]
@kpeckett You are right, but as part of the unification of the code, type-equality comparisons were removed where applicable and we should not use them, since they may introduce bugs.

**Review by itskdog — APPROVED** [review]
LGTM. Merging.

**Pull request merged**
